###################################################################################################
## This constraints file contains default clock frequencies to be used during creation of a 
## Synthesis Design Checkpoint (DCP). For best results the frequencies should be modified 
## to match the target frequencies. 
## This constraints file is not used in top-down/global synthesis (not the default flow of Vivado).
###################################################################################################


##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Wed Apr 24 10:45:53 2019

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       Top_mig_7series_0_0.xdc
##  Details :     Constraints file
##                    FPGA Family:       ARTIX7
##                    FPGA Part:         XC7A200T-FBG484
##                    Speedgrade:        -3
##                    Design Entry:      VERILOG
##                    Frequency:         533.33000000000004 MHz
##                    Time Period:       1875 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41K256M16XX-125
## Data Width: 16
## Time Period: 1875
## Data Mask: 1
##################################################################################################